### ISSUE TITLE
Nice (stealth) project!

### ISSUE THREAD

**Issue by pangloss** [lomin/chatda#1]
Hey Steven,

I read your associated blog post with interest and found my way here from there. I was surprised to see that despite this being a very nicely crafted piece of software it's missing the basic readme and docs essential to give people the confidence to adopt it. Are you planning to eventually release this project? I'd like to use it!

Best,
Darrick

**Comment by lomin** [comment]
Hi Darrick,

thanks for reaching out. This repository was actually only intended to support the blog posts. In the process of writing, I discover better and more performant ways to solve the tasks mentioned in the blog posts, which results to a rather volatile API. To comply with Clojure’s philosophy not to break things and because I thought nobody cares anyway, I was too lazy to publish anything publicly in a stable way. But if you have use for this project, I could invest some work to release something that matches Clojure’s standards. What exactly do you want to use? The search abstraction or the matcher build upon this abstraction?

Best,
Steven

**Comment by pangloss** [comment]
The piece that most interests me personally is the `=*` matcher you built. I pulled it into a project that I'm working on as a test dependency to try it out, and it works great! I'm sure there are plenty of people who'd benefit from using it as well who just don't know it exists yet.

For my own personal use, I'm happy to use the project as it is since I don't mind trying out alpha software, especially on the dev tools side, so no need to do anything to support me.

If it matters, I personally don't think you need to worry about releasing totally stable code. If it doesn't have much adoption it doesn't matter if you change it, or if it does and you want to make major changes, it's easy enough to just rename the project and move on!

Cheers,
Darrick

**Comment by lomin** [comment]
I moved the `=*` matcher to [lomin/sinho](https://github.com/lomin/sinho), and uploaded a 1.0.0 release of it to clojars, since the matcher itself is stable. I also added a basic README.

Here in this repository, things will continue to change and break, but will have no impact for the `=*` matcher.

Thanks for kicking this off, Darrick!
